### ISSUE TITLE
Vive tracker issue

### ISSUE THREAD

**Issue by 0xouzm** [acidbubbles/vam-embody#1]
Sorry , my vive tracker doesn't work after I compelted wizard with vive tracker 2-setp selected 
how can I enable my tracker in vam?
Do I miss something?

**Comment by 0xouzm** [comment]
In steam vr my tracker is detected

**Comment by 0xouzm** [comment]
Should I download some plugins for support? I found you said ViveTracker 1...8? in tracker wiki page,what does that mean？

**Comment by 0xouzm** [comment]
https://trello.com/c/KB0IqHb3/1253-note-on-vive-trackers-you-must-bind-them-in-steamvr-now-to-specific-roles-and-natural-locomotion-prevents-vam-from-seeing-them
I found this looks like the official docs, I will try it!

**Comment by acidbubbles** [comment]
Yeah someone else had the same issue, I added a note here: https://github.com/acidbubbles/vam-embody/wiki/Getting-started#vive-trackers

If you do find another reason, let me know and I'll document it :)

**Comment by 0xouzm** [comment]
I don't konw what Natural Locomotion is , seems I didn't installed it . But somehow I made my tracker worked, first you need right click your tracker in steamvr runtime manage window,choose manage your tracker, bind tracker on your waist，make sure your tracker actually appear in steam vr home, then exectute your embody wizard, I can meet the tracker manage page , Yeah you made one awesome plugin THANKS

**Comment by 0xouzm** [comment]
Maybe there are some other options I accidently opened. It's worth a try. I'm not 100 percent sure this way is right.

**Comment by acidbubbles** [comment]
In any case if someone else asks I'll refer them here. So if at least someone else founds this to be the solution, we'll know :)
